// models/enum.js

export const UserActionEnum = Object.freeze({
  SET_PIN: "SET-PIN",
  CHANGE_PIN: "CHANGE-PIN",
  WITHDRAWAL_REQUEST: "WITHDRAWAL-REQUEST",
  WITHDRAWAL_ACCEPT: "WITHDRAWAL-ACCEPT",
  WITHDRAWAL_REJECT: "WITHDRAWAL-REJECT",
  WITHDRAWAL_COMPLETED: "WITHDRAWAL-COMPLETED",
  CHANGE_PASSWORD: "CHANGE-PASSWORD",
  CAMPAIGN_STARTED: "CAMPAIGN_STARTED",
  ACCOUNT_DELETION: "ACCOUNT-DELETION",
  USER_REFER: "USER-REFER",
  COMMISSION_PAYOUT: "COMMISSION-PAYOUT",
  REWARD_CLAIM: "REWARD_CLAIM",
  REWARD_EARN: "REWARD_EARN",

});

export const UserCategoryEnum = Object.freeze({
  PAYOUT: "PAYOUT",
  ACTIONS: "ACTIONS",
  REGISTRATION: "REGISTRATION",
  CAMPAIGN: "CAMPAIGN",
  ADMIN: "ADMIN",
  GENERAL: "GENERAL",
  EARNINGS: "EARNINGS",
  REWARD: "REWARD",

});

export const UserTypeEnum = Object.freeze({
  USER: "USER",
  ADMIN: "ADMIN",
  SUPER_ADMIN: "SUPER_ADMIN",
});

export const statusEnum = Object.freeze({
  PENDING: "PENDING",
  APPROVED: "APPROVED",
  REJECTED: "REJECTED",
  BLOCKED: "BLOCKED",
  SUSPENDED:"SUSPENDED",
  PAUSED:"PAUSED"
});
